services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env  # Přidáno pro načtení API klíče
    networks:
      - app_network
    restart: always
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8000/api/hello" ]
        interval: 30s
        timeout: 10s
        retries: 3

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy  # Počká, až bude backend připraven
    networks:
      - app_network
    restart: always  # Restartuje frontend při pádu

networks:
  app_network:
    driver: bridge

volumes:
  logs:
